linux:
    hosts:
        manager:
            ansible_host: 15.188.194.190
            ansible_user: ubuntu
            ansible_ssh_private_key_file: /media/high-sparrow/Documents/studies/Master/.keys/paris_default.pem
