apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kserver-access-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kserver-access-role
subjects:
- kind: ServiceAccount
  name: kserver-access
  namespace:  kubeflow-user-example-com
