- name: "set up kubeflow"
  gather_facts: false
  hosts: manager
  tasks:
    - name: "copy the IAM role updater script"
      copy:
        src: "../config/update_IAM_role.py"
        dest: "/tmp/iam-role-updater.py"
        mode: 0755
    - name: "run the IAM role updater script"
      shell: "python3 /tmp/iam-role-updater.py"
    - name: "did you already set up the k8s cluster?"
      shell: "kubectl get nodes"
      register: k8s_cluster_status
      ignore_errors: true
    - name: "set up the k8s cluster"
      shell: "cd kubeflow-manifests/deployments/vanilla/terraform && make deploy"
      when: k8s_cluster_status.rc != 0